name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
# Test
jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: deployment
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - run: sudo apt install sshpass
    
    - run: ls
    - name: Sync folders
      run: 
        sshpass -p "${{ secrets.SSH_PASSWD }}" rsync -zvr -e "ssh -o StrictHostKeyChecking=no" dist/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOST_PATH }}"
